apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "verifyJob.name" . }}
  annotations:
    kapp.k14s.io/disable-wait: ""
  labels:
    app: {{ template "verifyJob.name" . }}
    release: {{ .Release.Name }}
spec:
  backoffLimit: 1
  completions: 1
  parallelism: 1
  template:
    metadata:
{{- if .Values.verifyJob.podAnnotations }}
      annotations:
{{ toYaml .Values.verifyJob.podAnnotations | indent 8 }}
{{- end }}
    spec:
      containers:
      - command:
        - jx-verify
        - pods
        env:
        - name: XDG_CONFIG_HOME
          value: /home
        image: {{ tpl .Values.image.repository . }}:{{ tpl .Values.image.tag . }}
        imagePullPolicy: {{ tpl .Values.image.pullPolicy . }}
        name: job
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      serviceAccountName: {{ template "verifyJob.saName" . }}
